sudo: required
services:
  - docker

if: tag IS present
branches:
  except:
  - /^untagged/
  
cache:
    directories:
     - $HOME/.cache

language: C

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - ./travis-build.sh

script:
  - mkdir -p build
  - docker run build-nginx-brotli
  - docker cp $(docker ps -l -q):/src build/
  - mv build/src/*.deb ./
  - rm -Rf build

env:
    matrix:
#      - OS=ubuntu DIST=trusty
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=bionic
#      - OS=ubuntu DIST=yakkety
#      - OS=debian DIST=jessie
#      - OS=debian DIST=wheezy
      - OS=debian DIST=stretch
      - OS=debian DIST=buster
#      - OS=ubuntu DIST=xenial ARCH=i386
#      - OS=debian DIST=jessie ARCH=i386

deploy:
  - provider: packagecloud
    username: ${PACKAGECLOUD_USER}
    repository: "libnginx-mod-brotli-stable"
    token: ${PACKAGECLOUD_TOKEN}
    dist: ${OS}/${DIST}
    skip_cleanup: true
    on:
      branch: stable
      tags: true
      condition: -n "${OS}" && -n "${DIST}" && -n "${PACKAGECLOUD_TOKEN}"
  - provider: releases
    api_key:
      secure: xb/uAbGcTznFcWG59/Xhoa6AliDa1MYoAuqJfcL+QUQIj8u1UUUEYCW99YILfTpPaXKCclXSiV8v1I1lIt7EupOvg87lfglf153QTQKRK/LXsC2NQNxq1xbSqn3j55O0OUWDCi6Y04pfCmgn8TrAgLeqVHhTLJtpk6rVoCk10OJfbd35eKVPILN9uY0VKyAQn5tzO8TlLeOOnwZ3+0AN6k3uaXynPjQwHIWkXwOjyEvVF+ibmGKJqn1I1IBNafnJ+FB3JKPa+nTynmEQbUUIvnRkOuxPEIwCb7UDK/El+QTu2CxoZxQVpurEW44SPcSBuBOm8AifUv3iyGduD1ji1R/7bnhxsAT5stinNn4GsJJTih929Da0s1Zmgg3CBLwUDVp5dBIUcTx7sZq57qw8kBwowj/gpy6u+jW7KZ0BihgaUAy/52klfU1qFQrfhxxoM3rfUws4ilvebDAl7gGsnsfHXX7BlRb6FAo9QLtRib5kpP+qu5IBe9OiwdLzF3xxa/LtcsBj3O4AZ6PNcaGO3WvA8ar44sa2ZJckghvigZXabLm4Ut7rQElpCmG8uyi4lF2abmzSF/y+FOZmKGwAVb9nR+heJeGC8eC38PUYLCgIIJ0VPHYyYTrzBJlAz+VTb4KxZ3g3c7T+7/Gu+947/D5BW/rQPzNWpZaDTM0wyO0=
    file_glob: true
    file: ./*.deb
    skip_cleanup: true
    on:
      branch: stable
      tags: true
    tag_name: $TRAVIS_TAG
